apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: elw1mzpkm-nodejs 
  janus-idp.io/tekton: elw1mzpkm-nodejs
  backstage.io/kubernetes-id: elw1mzpkm-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: elw1mzpkm-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml