apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: elw1mzpkm-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: elw1mzpkm-nodejs 
  name: elw1mzpkm-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: elw1mzpkm-nodejs 
